import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Bookmark, Check, Heart, MessageCircle, MoreHorizontal, Play, Send, Volume2 } from "lucide-react";
import feed from "@/assets/feed-cobalt.jpg";
import wheel from "@/assets/wheel-product.jpg";
import { AppShell, Brand } from "@/components/avtoqism-shell";
import { SellerLine } from "@/components/avtoqism-ui";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/feed")({ head: () => ({ meta: [{ title: "Avto Feed — AVTOQISM" }, { name: "description", content: "O‘zbekiston avtomobil ishqibozlari uchun qisqa videolar va mos mahsulotlar." }, { property: "og:title", content: "Avto Feed — AVTOQISM" }, { property: "og:description", content: "Avtomobillar, ustalar va sizning mashinangizga mos qismlar." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Feed });

function Feed(){const [liked,setLiked]=useState(false);const [saved,setSaved]=useState(false);return <AppShell dark><main className="relative mx-auto min-h-screen max-w-[1440px] overflow-hidden pb-16 md:grid md:grid-cols-[minmax(0,1fr)_390px] md:pb-0">
  <header className="absolute inset-x-0 top-0 z-20 flex h-20 items-center justify-between px-5 md:px-8"><Brand inverse/><div className="flex items-center gap-5"><span className="border-b-2 border-primary pb-2 text-sm font-semibold">Siz uchun</span><span className="pb-2 text-sm text-feed-muted">Kuzatuvlar</span><Button variant="ghost" size="icon" className="text-feed-foreground" aria-label="Ko‘proq"><MoreHorizontal/></Button></div></header>
  <section className="relative min-h-[calc(100vh-4rem)] md:min-h-screen"><img src={feed} alt="Toshkent oqshomida Chevrolet Cobalt" width={1200} height={1500} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-feed via-transparent to-feed/30"/><button aria-label="Videoni ijro etish" className="absolute inset-0 m-auto grid size-16 place-items-center rounded-full border border-feed-border bg-feed/25 text-feed-foreground backdrop-blur-sm"><Play className="ml-1 size-6 fill-current"/></button><div className="absolute bottom-5 left-5 right-5 z-10 md:bottom-8 md:left-8 md:right-8"><div className="max-w-xl"><SellerLine dark/><p className="mt-5 text-lg font-medium leading-relaxed">Cobalt uchun shahar uslubi. R17 graphite disklar bilan yangi ko‘rinish — sokin, aniq, o‘ziga xos.</p><div className="mt-4 flex items-center gap-2 text-sm text-feed-muted"><span>#cobalt</span><span>#toshkent</span><span>#avtoqism</span></div></div></div><Button variant="ghost" size="icon" className="absolute right-5 top-24 text-feed-foreground" aria-label="Ovoz"><Volume2/></Button>
  <div className="absolute bottom-8 right-5 z-20 flex flex-col gap-5 md:right-8">{[[Heart,liked,"12.4K",()=>setLiked(!liked)],[MessageCircle,false,"286",()=>{}],[Send,false,"Ulashish",()=>{}],[Bookmark,saved,"Saqlash",()=>setSaved(!saved)]].map(([Icon,on,label,click])=>{const I=Icon as typeof Heart;return <button key={String(label)} onClick={click as ()=>void} className="flex flex-col items-center gap-1 text-[10px] font-semibold text-feed-foreground"><span className="grid size-11 place-items-center rounded-full bg-feed/45 backdrop-blur-sm"><I className={`size-5 ${on?"fill-primary text-primary":""}`}/></span>{String(label)}</button>})}</div></section>
  <aside className="hidden border-l border-feed-border bg-feed p-8 md:flex md:flex-col md:justify-end"><p className="text-xs font-bold uppercase tracking-[.14em] text-feed-muted">Videodagi mahsulot</p><div className="mt-5 aspect-[4/3] overflow-hidden"><img src={wheel} alt="R17 Graphite disk" width={1200} height={1500} loading="lazy" className="h-full w-full object-cover"/></div><h1 className="mt-6 font-display text-2xl font-semibold">R17 Graphite disk va shina</h1><p className="mt-2 text-xl font-semibold">6 490 000 so‘m</p><div className="mt-5 flex items-center gap-3 border-y border-feed-border py-4"><span className="grid size-7 place-items-center rounded-full bg-success"><Check className="size-4"/></span><div><p className="text-xs font-bold uppercase tracking-[.1em] text-success">Mos keladi</p><p className="mt-1 text-sm text-feed-muted">Chevrolet Cobalt · 2023</p></div></div><Button variant="feed" size="xl" className="mt-6 w-full" asChild><Link to="/product">Mahsulotni ko‘rish</Link></Button></aside>
  <Link to="/product" className="absolute bottom-24 left-5 right-20 z-30 flex items-center gap-3 border border-feed-border bg-feed/70 p-3 backdrop-blur-md md:hidden"><img src={wheel} alt="" width={56} height={56} className="size-14 object-cover"/><div className="min-w-0"><p className="truncate text-sm font-semibold">R17 Graphite disk</p><p className="text-xs text-feed-muted">6 490 000 so‘m</p></div></Link>
  </main></AppShell>}