import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, ChevronRight, Gauge, Plus, Settings2, ShieldCheck } from "lucide-react";
import cobalt from "@/assets/cobalt-hero.jpg";
import { AppShell, SectionHeading } from "@/components/avtoqism-shell";
import { ProductCard, products } from "@/components/avtoqism-ui";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/garage")({ head: () => ({ meta: [{ title: "Mening garajim — AVTOQISM" }, { name: "description", content: "Chevrolet Cobalt uchun mos qismlar va avtomobil profili." }, { property: "og:title", content: "Mening garajim — AVTOQISM" }, { property: "og:description", content: "Avtomobilingiz, uning ma’lumotlari va mos mahsulotlar bir joyda." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Garage });

function Garage() { return <AppShell><main className="pb-28 md:pb-16">
  <section className="mx-auto max-w-[1440px] px-5 pb-16 pt-10 lg:px-10 lg:pt-16"><div className="mb-8 flex items-center justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.16em] text-primary">Mening garajim</p><h1 className="font-display text-4xl font-semibold md:text-6xl">Bu — sizning Cobalt’ingiz.</h1></div><Button variant="outline" className="hidden md:inline-flex"><Plus /> Avtomobil qo‘shish</Button></div>
  <div className="grid overflow-hidden border border-border bg-card lg:grid-cols-[1.6fr_.9fr]"><div className="min-h-[340px] overflow-hidden lg:min-h-[590px]"><img src={cobalt} alt="Oq Chevrolet Cobalt 2023" width={1920} height={1200} className="h-full w-full object-cover" /></div><div className="flex flex-col justify-between p-6 md:p-10"><div><span className="inline-flex items-center gap-2 bg-success-soft px-3 py-2 text-xs font-bold uppercase tracking-[.1em] text-success"><Check className="size-4" /> Asosiy avtomobil</span><h2 className="mt-8 font-display text-3xl font-semibold">Chevrolet Cobalt</h2><p className="mt-2 text-muted-foreground">2023 · 1.5 · Automatic</p><dl className="mt-10 divide-y divide-border border-y border-border">{[["Davlat raqami","01 A 777 VA"],["Kuzov rangi","Oq metallik"],["Yurgan masofa","32 480 km"],["VIN","XWB••••••••0472"]].map(([a,b])=><div key={a} className="flex justify-between py-4 text-sm"><dt className="text-muted-foreground">{a}</dt><dd className="font-semibold">{b}</dd></div>)}</dl></div><div className="mt-8 grid grid-cols-2 gap-3"><div className="border border-border p-4"><Gauge className="mb-5 size-5 text-primary"/><p className="text-xs text-muted-foreground">Keyingi servis</p><p className="mt-1 font-semibold">2 520 km</p></div><div className="border border-border p-4"><ShieldCheck className="mb-5 size-5 text-primary"/><p className="text-xs text-muted-foreground">Moslik aniqligi</p><p className="mt-1 font-semibold">Tasdiqlangan</p></div></div></div></div>
  <Button className="mt-4 w-full md:hidden" size="lg"><Plus /> Avtomobil qo‘shish</Button></section>
  <section className="border-t border-border"><div className="mx-auto max-w-[1440px] px-5 py-14 lg:px-10"><SectionHeading eyebrow="Aniq tanlov" title="Cobalt’ingizga mos" action={<Link to="/product" className="hidden items-center gap-1 text-sm font-semibold md:flex">Barchasini ko‘rish <ChevronRight className="size-4"/></Link>} /><div className="grid grid-cols-2 gap-5 md:grid-cols-3 lg:gap-8">{products.map((p)=><ProductCard key={p.name} product={p}/>)}</div></div></section>
  <div className="fixed bottom-20 right-5 md:bottom-8 md:right-8"><Button size="icon" className="size-12 rounded-full shadow-lg" aria-label="Garaj sozlamalari"><Settings2 /></Button></div>
  </main></AppShell>; }