import { createFileRoute } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";
import { ArrowRight, ChevronRight, MapPin, Play, ShieldCheck } from "lucide-react";
import cobalt from "@/assets/cobalt-hero.jpg";
import feed from "@/assets/feed-cobalt.jpg";
import headlights from "@/assets/headlights.jpg";
import { AppShell, SectionHeading } from "@/components/avtoqism-shell";
import { ProductCard, products } from "@/components/avtoqism-ui";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "AVTOQISM — Avtomobilingiz uchun aniq tanlov" }, { name: "description", content: "Chevrolet Cobalt uchun mos ehtiyot qismlar, ishonchli sotuvchilar va avtomobil videolari." }, { property: "og:title", content: "AVTOQISM — Avtomobilingiz uchun aniq tanlov" }, { property: "og:description", content: "Garajingizdan boshlanadigan premium avtomobil savdosi." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: Index,
});

// IMPORTANT: Replace this placeholder. See ./README.md for routing conventions.
function Index() {
  return <AppShell><main className="pb-24 md:pb-0">
    <section className="mx-auto grid max-w-[1440px] gap-8 px-5 pb-16 pt-8 lg:grid-cols-[.78fr_1.22fr] lg:px-10 lg:pb-24 lg:pt-14"><div className="enter-rise flex flex-col justify-center"><p className="mb-5 text-xs font-bold uppercase tracking-[.18em] text-primary">Sizning avtomobilingiz</p><h1 className="font-display text-5xl font-semibold leading-[1.05] md:text-7xl">Chevrolet<br/>Cobalt</h1><p className="mt-5 text-lg text-muted-foreground">2023 · 1.5 · Automatic</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/garage">Garajni ochish <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><Link to="/product">Mos qismlar</Link></Button></div><div className="mt-12 flex items-center gap-3 border-t border-border pt-5 text-sm text-muted-foreground"><ShieldCheck className="size-5 text-success"/> 2 840 ta mahsulot mosligi tekshirilgan</div></div><div className="relative min-h-[390px] overflow-hidden bg-muted lg:min-h-[600px]"><img src={cobalt} alt="Chevrolet Cobalt 2023" width={1920} height={1200} className="h-full w-full object-cover"/><div className="absolute bottom-4 left-4 bg-background px-4 py-3 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">Garaj statusi</p><p className="mt-1 text-sm font-semibold">Moslik faol</p></div></div></section>
    <section className="border-y border-border bg-card"><div className="mx-auto max-w-[1440px] px-5 py-14 lg:px-10"><SectionHeading eyebrow="Siz uchun" title="Cobalt’ingizga mos" action={<Link to="/garage" className="flex items-center gap-1 text-sm font-semibold">Barchasi <ChevronRight className="size-4"/></Link>}/><div className="grid grid-cols-2 gap-5 md:grid-cols-3 lg:gap-8">{products.map(p=><ProductCard key={p.name} product={p}/>)}</div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-16 lg:px-10"><SectionHeading eyebrow="Trendda" title="Hozir ko‘p tanlanmoqda"/><div className="grid gap-5 md:grid-cols-2"><Link to="/product" className="group relative min-h-[400px] overflow-hidden"><img src={headlights} alt="Cobalt Bi-LED faralari" width={1200} height={900} loading="lazy" className="image-zoom absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-feed/80 to-transparent"/><div className="absolute bottom-0 p-7 text-feed-foreground"><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Trend #01</p><h3 className="mt-2 font-display text-2xl font-semibold">Tun uchun yangi nigoh</h3><p className="mt-2 text-sm text-feed-muted">Bi-LED faralar · 3 850 000 so‘m</p></div></Link><Link to="/feed" className="group relative min-h-[400px] overflow-hidden"><img src={feed} alt="Toshkentdagi Cobalt videosi" width={1200} height={1500} loading="lazy" className="image-zoom absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-feed/80 to-transparent"/><div className="absolute inset-0 grid place-items-center"><span className="grid size-14 place-items-center rounded-full bg-background/90 text-foreground"><Play className="ml-1 fill-current"/></span></div><div className="absolute bottom-0 p-7 text-feed-foreground"><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Tavsiya etilgan video</p><h3 className="mt-2 font-display text-2xl font-semibold">Toshkent oqshomida Cobalt</h3></div></Link></div></section>
    <section className="border-y border-border"><div className="mx-auto max-w-[1440px] px-5 py-14 lg:px-10"><SectionHeading eyebrow="Yaqiningizda" title="Ishonchli sotuvchilar"/><div className="grid gap-px bg-border md:grid-cols-3">{[["AvtoMax","Sergeli · 1.8 km","4.9"],["Detal Market","Chilonzor · 3.2 km","4.8"],["Cobalt House","Yakkasaroy · 4.1 km","4.9"]].map(([name,place,rating])=><div key={name} className="bg-background p-6"><div className="flex items-start justify-between"><div className="grid size-11 place-items-center rounded-full bg-foreground text-xs font-bold text-background">{name.slice(0,2).toUpperCase()}</div><span className="text-sm font-semibold">★ {rating}</span></div><h3 className="mt-8 font-display text-xl font-semibold">{name}</h3><p className="mt-2 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-4"/>{place}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-16 lg:px-10"><SectionHeading eyebrow="Kategoriyalar" title="Keraklisini tez toping"/><div className="grid grid-cols-2 border-l border-t border-border md:grid-cols-4">{["Disk va shinalar","Yoritish","Salon","Ehtiyot qismlar","Audio","Avtokimyo","Tashqi ko‘rinish","Servis"].map((c,i)=><Link key={c} to="/product" className="group flex min-h-32 flex-col justify-between border-b border-r border-border p-5 transition-colors hover:bg-muted"><span className="text-xs text-muted-foreground">0{i+1}</span><span className="flex items-end justify-between font-semibold">{c}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></Link>)}</div></section>
  </main></AppShell>;
}
