import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Check, ChevronLeft, ChevronRight, Heart, PackageCheck, ShieldCheck, ShoppingBag, Truck } from "lucide-react";
import wheel from "@/assets/wheel-product.jpg";
import headlights from "@/assets/headlights.jpg";
import cobalt from "@/assets/cobalt-hero.jpg";
import { AppShell } from "@/components/avtoqism-shell";
import { Rating, SellerLine } from "@/components/avtoqism-ui";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/product")({ head: () => ({ meta: [{ title: "R17 Graphite disk va shina — AVTOQISM" }, { name: "description", content: "Chevrolet Cobalt uchun R17 premium disk va shina to‘plami." }, { property: "og:title", content: "R17 Graphite disk va shina — AVTOQISM" }, { property: "og:description", content: "Chevrolet Cobalt 2023 uchun mosligi tasdiqlangan premium to‘plam." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Product });

function Product() { const gallery=[wheel,headlights,cobalt]; const [active,setActive]=useState(0); const [saved,setSaved]=useState(false); return <AppShell><main className="mx-auto max-w-[1440px] px-5 pb-28 pt-6 lg:px-10 lg:pb-20 lg:pt-10">
  <div className="mb-7 flex items-center justify-between"><button onClick={()=>history.back()} className="flex items-center gap-2 text-sm font-semibold"><ChevronLeft className="size-4"/> Katalogga qaytish</button><Button variant="ghost" size="icon" onClick={()=>setSaved(!saved)} aria-label="Saqlash"><Heart className={saved ? "fill-primary text-primary" : ""}/></Button></div>
  <div className="grid gap-10 lg:grid-cols-[1.2fr_.8fr] lg:gap-16"><section><div className="relative aspect-[4/3] overflow-hidden bg-muted"><img src={gallery[active]} alt="R17 Graphite disk va shina" width={1200} height={1500} className="h-full w-full object-cover"/><div className="absolute bottom-4 right-4 flex gap-2"><Button variant="outline" size="icon" aria-label="Oldingi rasm" onClick={()=>setActive((active+2)%3)}><ChevronLeft/></Button><Button variant="outline" size="icon" aria-label="Keyingi rasm" onClick={()=>setActive((active+1)%3)}><ChevronRight/></Button></div></div><div className="mt-3 grid grid-cols-3 gap-3">{gallery.map((image,i)=><button key={image} onClick={()=>setActive(i)} className={`aspect-[4/3] overflow-hidden border-2 ${active===i?"border-primary":"border-transparent"}`} aria-label={`${i+1}-rasm`}><img src={image} alt="" width={300} height={225} loading="lazy" className="h-full w-full object-cover"/></button>)}</div></section>
  <section className="lg:sticky lg:top-28 lg:self-start"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Yangi kolleksiya</p><h1 className="mt-4 font-display text-3xl font-semibold leading-tight md:text-5xl">R17 Graphite disk va shina to‘plami</h1><div className="mt-5 flex items-center justify-between border-b border-border pb-6"><Rating/><span className="text-xs text-muted-foreground">Art. AQ-17490</span></div><p className="mt-7 font-display text-3xl font-semibold">6 490 000 so‘m</p><p className="mt-3 text-sm leading-6 text-muted-foreground">4 dona yengil qotishmali disk va premium klassdagi yozgi shinalar. Muvozanatlash xizmati narx ichida.</p>
  <div className="mt-7 border border-success bg-success-soft p-5"><div className="flex items-start gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-full bg-success text-primary-foreground"><Check className="size-5"/></div><div><p className="text-sm font-bold uppercase tracking-[.1em] text-success">Mos keladi</p><p className="mt-2 font-semibold">Chevrolet Cobalt</p><p className="text-sm text-muted-foreground">2023 · 1.5 · Automatic</p></div></div></div>
  <div className="mt-6 grid grid-cols-2 gap-3"><Button size="xl"><ShoppingBag/> Savatga qo‘shish</Button><Button size="xl" variant="outline">Hoziroq olish</Button></div>
  <div className="mt-8 divide-y divide-border border-y border-border">{[[PackageCheck,"Omborda bor","Bugun jo‘natiladi"],[Truck,"Yetkazib berish","Toshkent bo‘ylab 1 kun"],[ShieldCheck,"Kafolat","12 oy rasmiy kafolat"]].map(([Icon,a,b])=>{const I=Icon as typeof PackageCheck;return <div key={String(a)} className="flex items-center gap-4 py-4"><I className="size-5 text-primary"/><div><p className="text-sm font-semibold">{String(a)}</p><p className="text-xs text-muted-foreground">{String(b)}</p></div></div>})}</div>
  <div className="mt-8"><p className="mb-4 text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">Sotuvchi</p><div className="flex items-center justify-between border border-border p-5"><SellerLine/><Button variant="ghost" size="sm">Profil</Button></div></div></section></div>
  </main></AppShell>; }